striver_plus_ques_list = {
    "Count all digits of a number": "https://www.geeksforgeeks.org/program-count-digits-integer-3-different-methods/",
    "Count number of odd digits in a number": "https://www.geeksforgeeks.org/count-odd-digits-number/",
    "Reverse a number": "https://www.geeksforgeeks.org/write-a-program-to-reverse-digits-of-a-number/",
    "Palindrome number": "https://leetcode.com/problems/palindrome-number/",
    "Return the largest digit in a number": "https://www.geeksforgeeks.org/find-largest-digit-number/",
    "Factorial of a given number": "https://www.geeksforgeeks.org/program-for-factorial-of-a-number/",
    "Check if the number is armstrong": "https://www.geeksforgeeks.org/program-for-armstrong-numbers/",
    "Check for perfect number": "https://www.geeksforgeeks.org/perfect-number/",
    "Check for prime number": "https://www.geeksforgeeks.org/python-program-to-check-whether-a-number-is-prime-or-not/",
    "Count of prime numbers till N": "https://leetcode.com/problems/count-primes/",
    "GCD of two numbers": "https://www.geeksforgeeks.org/gcd-two-numbers/",
    "LCM of two numbers": "https://www.geeksforgeeks.org/lcm-two-numbers/",
    "Divisors of a number": "https://www.geeksforgeeks.org/find-divisors-natural-number-set-1/",
    "Sum of array elements": "https://www.geeksforgeeks.org/program-find-sum-elements-given-array/",
    "Count of odd numbers in array": "https://www.geeksforgeeks.org/count-odd-even-numbers-array/",
    "Reverse an array": "https://www.geeksforgeeks.org/write-a-program-to-reverse-an-array-or-string/",
    "Check if the array is sorted": "https://www.geeksforgeeks.org/check-if-array-is-sorted/",
    "Highest occurring element in an array": "https://www.geeksforgeeks.org/frequent-element-array/",
    "Second highest occurring element": "https://www.geeksforgeeks.org/find-the-second-most-frequent-character/",
    "Sum of highest and lowest frequency": "https://www.geeksforgeeks.org/sum-of-maximum-and-minimum-frequency-of-elements-in-an-array/",
    "Reverse a string": "https://leetcode.com/problems/reverse-string/",
    "Palindrome Check": "https://leetcode.com/problems/valid-palindrome/",
    "Largest odd number in a string": "https://leetcode.com/problems/largest-odd-number-in-string/",
    "Longest common prefix": "https://leetcode.com/problems/longest-common-prefix/",
    "Isomorphic string": "https://leetcode.com/problems/isomorphic-strings/",
    "Rotate string": "https://leetcode.com/problems/rotate-string/",
    "Valid Anagram": "https://leetcode.com/problems/valid-anagram/",
    "Sort characters by frequency": "https://leetcode.com/problems/sort-characters-by-frequency/",
    "Recursion Theory": "https://www.geeksforgeeks.org/recursion/",
    "Recursion Concepts with Parameters": "https://www.geeksforgeeks.org/recursion/",
    "Sum of first N numbers": "https://www.geeksforgeeks.org/sum-of-first-n-natural-numbers/",
    "Factorial of a given number": "https://www.geeksforgeeks.org/program-for-factorial-of-a-number/",
    "Sum of array elements": "https://www.geeksforgeeks.org/program-find-sum-elements-given-array/",
    "Reverse a string": "https://leetcode.com/problems/reverse-string/",
    "Check if string is palindrome or not": "https://leetcode.com/problems/valid-palindrome/",
    "Check if a number is prime or not": "https://www.geeksforgeeks.org/python-program-to-check-whether-a-number-is-prime-or-not/",
    "Reverse an array": "https://www.geeksforgeeks.org/write-a-program-to-reverse-an-array-or-string/",
    "Check if the array is sorted": "https://www.geeksforgeeks.org/check-if-array-is-sorted/",
    "Sum of digits in a given number": "https://www.geeksforgeeks.org/program-for-sum-of-the-digits-of-a-given-number/",
    "Fibonacci Number": "https://leetcode.com/problems/fibonacci-number/",
    "Selection Sort": "https://www.geeksforgeeks.org/selection-sort/",
    "Bubble Sort": "https://www.geeksforgeeks.org/bubble-sort/",
    "Insertion Sorting": "https://www.geeksforgeeks.org/insertion-sort/",
    "Merge Sorting": "https://www.geeksforgeeks.org/merge-sort/",
    "Quick Sorting": "https://www.geeksforgeeks.org/quick-sort/",
    "Linear Search": "https://www.geeksforgeeks.org/linear-search/",
    "Largest Element": "https://leetcode.com/problems/largest-element-in-an-array/",
    "Second Largest Element": "https://www.geeksforgeeks.org/find-second-largest-element-array/",
    "Maximum Consecutive Ones": "https://leetcode.com/problems/max-consecutive-ones/",
    "Left Rotate Array by One": "https://www.geeksforgeeks.org/left-rotate-array-one/",
    "Left Rotate Array by K Places": "https://leetcode.com/problems/rotate-array/",
    "Move Zeros to End": "https://leetcode.com/problems/move-zeroes/",
    "Remove duplicates from sorted array": "https://leetcode.com/problems/remove-duplicates-from-sorted-array/",
    "Find missing number": "https://leetcode.com/problems/missing-number/",
    "Union of two sorted arrays": "https://www.geeksforgeeks.org/union-and-intersection-of-two-sorted-arrays-2/",
    "Intersection of two sorted arrays": "https://leetcode.com/problems/intersection-of-two-arrays/",
    "Leaders in an Array": "https://www.geeksforgeeks.org/leaders-in-an-array/",
    "Print the matrix in spiral manner": "https://leetcode.com/problems/spiral-matrix/",
    "Rearrange array elements by sign": "https://leetcode.com/problems/rearrange-array-elements-by-sign/",
    "Pascal's Triangle": "https://leetcode.com/problems/pascals-triangle/",
    "Rotate matrix by 90 degrees": "https://leetcode.com/problems/rotate-image/",
    "Two Sum": "https://leetcode.com/problems/two-sum/",
    "3 Sum": "https://leetcode.com/problems/3sum/",
    "4 Sum": "https://leetcode.com/problems/4sum/",
    "Sort an array of 0's 1's and 2's": "https://leetcode.com/problems/sort-colors/",
    "Kadane's Algorithm": "https://leetcode.com/problems/maximum-subarray/",
    "Majority Element-I": "https://leetcode.com/problems/majority-element/",
    "Majority Element-II": "https://leetcode.com/problems/majority-element-ii/",
    "Find the repeating and missing number": "https://www.geeksforgeeks.org/find-the-repeating-and-the-missing/",
    "Count Inversions": "https://www.geeksforgeeks.org/counting-inversions/",
    "Reverse Pairs": "https://leetcode.com/problems/reverse-pairs/",
    "Maximum Product Subarray in an Array": "https://leetcode.com/problems/maximum-product-subarray/",
    "Merge two sorted arrays without extra space": "https://www.geeksforgeeks.org/merge-two-sorted-arrays-o1-extra-space/",
    "Longest Consecutive Sequence in an Array": "https://leetcode.com/problems/longest-consecutive-sequence/",
    "Longest subarray with sum K": "https://www.geeksforgeeks.org/longest-sub-array-with-sum-k/",
    "Count subarrays with given sum": "https://www.geeksforgeeks.org/number-subarrays-sum-exactly-equal-k/",
    "Count subarrays with given xor K": "https://www.geeksforgeeks.org/count-number-subarrays-given-xor/",
    "Search X in sorted array": "https://leetcode.com/problems/binary-search/",
    "Lower Bound": "https://www.geeksforgeeks.org/lower-bound-on-a-sorted-vector-in-cpp/",
    "Upper Bound": "https://www.geeksforgeeks.org/upper_bound-in-cpp/",
    "Search insert position": "https://leetcode.com/problems/search-insert-position/",
    "Floor and Ceil in Sorted Array": "https://www.geeksforgeeks.org/floor-and-ceil-from-a-bst/",
    "First and last occurrence": "https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/",
    "Search in rotated sorted array-I": "https://leetcode.com/problems/search-in-rotated-sorted-array/",
    "Search in rotated sorted array-II": "https://leetcode.com/problems/search-in-rotated-sorted-array-ii/",
    "Find minimum in Rotated Sorted Array": "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/",
    "Find out how many times the array is rotated": "https://www.geeksforgeeks.org/find-rotation-count-rotated-sorted-array/",
    "Single element in sorted array": "https://leetcode.com/problems/single-element-in-a-sorted-array/",
    "Find square root of a number": "https://leetcode.com/problems/sqrtx/",
    "Find Nth root of a number": "https://www.geeksforgeeks.org/n-th-root-number/",
    "Find the smallest divisor": "https://leetcode.com/problems/find-the-smallest-divisor-given-a-threshold/",
    "Koko eating bananas": "https://leetcode.com/problems/koko-eating-bananas/",
    "Minimum days to make M bouquets": "https://leetcode.com/problems/minimum-number-of-days-to-make-m-bouquets/",
    "Aggressive Cows": "https://www.spoj.com/problems/AGGRCOW/",
    "Book Allocation Problem": "https://www.geeksforgeeks.org/allocate-minimum-number-pages/",
    "Find peak element": "https://leetcode.com/problems/find-peak-element/",
    "Median of 2 sorted arrays": "https://leetcode.com/problems/median-of-two-sorted-arrays/",
    "Minimise max distance to gas stations": "https://leetcode.com/problems/minimize-max-distance-to-gas-station/",
    "Kth element of 2 sorted arrays": "https://www.geeksforgeeks.org/k-th-element-two-sorted-arrays/",
    "Split array - largest sum": "https://leetcode.com/problems/split-array-largest-sum/",
    "Find row with maximum 1's": "https://leetcode.com/problems/row-with-maximum-ones/",
    "Search in a 2D matrix": "https://leetcode.com/problems/search-a-2d-matrix/",
    "Search in 2D matrix - II": "https://leetcode.com/problems/search-a-2d-matrix-ii/",
    "Find Peak Element": "https://leetcode.com/problems/find-peak-element/",
    "Matrix Median": "https://www.interviewbit.com/problems/matrix-median/",
    "Pow(x,n)": "https://leetcode.com/problems/powx-n/",
    "Generate Paranthesis": "https://leetcode.com/problems/generate-parentheses/",
    "Power Set": "https://leetcode.com/problems/subsets/",
    "Check if there exists a subsequence with sum K": "https://www.geeksforgeeks.org/subset-sum-problem-dp-25/",
    "Count all subsequences with sum K": "https://www.geeksforgeeks.org/count-subsequences-sum-given-number/",
    "Combination Sum": "https://leetcode.com/problems/combination-sum/",
    "Combination Sum II": "https://leetcode.com/problems/combination-sum-ii/",
    "Subsets I": "https://leetcode.com/problems/subsets/",
    "Subsets II": "https://leetcode.com/problems/subsets-ii/",
    "Combination Sum III": "https://leetcode.com/problems/combination-sum-iii/",
    "Letter Combinations of a Phone Number": "https://leetcode.com/problems/letter-combinations-of-a-phone-number/",
    "Palindrome partitioning": "https://leetcode.com/problems/palindrome-partitioning/",
    "Word Search": "https://leetcode.com/problems/word-search/",
    "N Queen": "https://leetcode.com/problems/n-queens/",
    "Rat in a Maze": "https://www.geeksforgeeks.org/rat-in-a-maze-backtracking-2/",
    "M Coloring Problem": "https://www.geeksforgeeks.org/m-coloring-problem-backtracking-5/",
    "Sudoko Solver": "https://leetcode.com/problems/sudoku-solver/",
    "Introduction to Singly LinkedList": "https://www.geeksforgeeks.org/introduction-to-linked-list-data-structure/",
    "Traversal in Linked List": "https://www.geeksforgeeks.org/linked-list-set-1-introduction/",
    "Deletion in Linked List": "https://www.geeksforgeeks.org/delete-a-node-in-a-linked-list/",
    "Insertion in Linked List": "https://www.geeksforgeeks.org/linked-list-set-2-inserting-a-node/",
    "Deletion of the head of LL": "https://www.geeksforgeeks.org/delete-a-node-in-a-linked-list/",
    "Deletion of the tail of LL": "https://www.geeksforgeeks.org/delete-a-node-in-a-linked-list/",
    "Deletion of the Kth element of LL": "https://www.geeksforgeeks.org/delete-a-node-in-a-linked-list/",
    "Delete the element with value X": "https://www.geeksforgeeks.org/delete-a-node-in-a-linked-list/",
    "Insertion at the head of LL": "https://www.geeksforgeeks.org/linked-list-set-2-inserting-a-node/",
    "Insertion at the tail of LL": "https://www.geeksforgeeks.org/linked-list-set-2-inserting-a-node/",
    "Insertion at the Kth position of LL": "https://www.geeksforgeeks.org/linked-list-set-2-inserting-a-node/",
    "Insertion before the value X in LL": "https://www.geeksforgeeks.org/linked-list-set-2-inserting-a-node/",
    "Introduction to Doubly LL": "https://www.geeksforgeeks.org/doubly-linked-list/",
    "Deletion in Doubly LL": "https://www.geeksforgeeks.org/delete-a-node-in-a-doubly-linked-list/",
    "Insertion in DLL": "https://www.geeksforgeeks.org/doubly-linked-list/",
    "Convert Array to DLL": "https://www.geeksforgeeks.org/convert-array-to-doubly-linked-list/",
    "Delete head of DLL": "https://www.geeksforgeeks.org/delete-a-node-in-a-doubly-linked-list/",
    "Delete Tail of DLL": "https://www.geeksforgeeks.org/delete-a-node-in-a-doubly-linked-list/",
    "Delete Kth Element of DLL": "https://www.geeksforgeeks.org/delete-a-node-in-a-doubly-linked-list/",
    "Removing given node in DLL": "https://www.geeksforgeeks.org/delete-a-node-in-a-doubly-linked-list/",
    "Insert node before head in DLL": "https://www.geeksforgeeks.org/doubly-linked-list/",
    "Insert node before tail in DLL": "https://www.geeksforgeeks.org/doubly-linked-list/",
    "Insert node before (kth node) in DLL": "https://www.geeksforgeeks.org/doubly-linked-list/",
    "Insert before given node in DLL": "https://www.geeksforgeeks.org/doubly-linked-list/",
    "Add two numbers in LL": "https://leetcode.com/problems/add-two-numbers/",
    "Segregate odd and even nodes in LL": "https://www.geeksforgeeks.org/segregate-even-and-odd-elements-in-a-linked-list/",
    "Sort a LL of 0's 1's and 2's": "https://www.geeksforgeeks.org/sort-a-linked-list-of-0s-1s-or-2s/",
    "Remove Nth node from the back of the LL": "https://leetcode.com/problems/remove-nth-node-from-end-of-list/",
    "Reverse a LL": "https://leetcode.com/problems/reverse-linked-list/",
    "Add one to a number represented by LL": "https://www.geeksforgeeks.org/add-1-number-represented-linked-list/",
    "Check if LL is palindrome or not": "https://leetcode.com/problems/palindrome-linked-list/",
    "Find the intersection point of Y LL": "https://leetcode.com/problems/intersection-of-two-linked-lists/",
    "Detect a loop in LL": "https://leetcode.com/problems/linked-list-cycle/",
    "Find the starting point in LL": "https://leetcode.com/problems/linked-list-cycle-ii/",
    "Length of loop in LL": "https://www.geeksforgeeks.org/find-length-of-loop-in-linked-list/",
    "Delete the middle node in LL": "https://leetcode.com/problems/delete-the-middle-node-of-a-linked-list/",
    "Reverse LL in group of given size K": "https://leetcode.com/problems/reverse-nodes-in-k-group/",
    "Rotate a LL": "https://leetcode.com/problems/rotate-list/",
    "Merge two Sorted Lists": "https://leetcode.com/problems/merge-two-sorted-lists/",
    "Flattening of LL": "https://www.geeksforgeeks.org/flattening-a-linked-list/",
    "Sort LL": "https://leetcode.com/problems/sort-list/",
    "Clone a LL with random and next pointer": "https://leetcode.com/problems/copy-list-with-random-pointer/",
    "Delete all occurrences of a key in DLL": "https://www.geeksforgeeks.org/delete-all-occurrences-of-a-given-key-in-a-doubly-linked-list/",
    "Remove duplicated from sorted DLL": "https://www.geeksforgeeks.org/remove-duplicates-sorted-doubly-linked-list/",
    "Introduction to Bits and Tricks": "https://www.geeksforgeeks.org/bitwise-hacks-for-competitive-programming/",
    "Minimum Bit Flips to Convert Number": "https://leetcode.com/problems/minimum-bit-flips-to-convert-number/",
    "Single Number - I": "https://leetcode.com/problems/single-number/",
    "Single Number - II": "https://leetcode.com/problems/single-number-ii/",
    "Single Number - III": "https://leetcode.com/problems/single-number-iii/",
    "Divide two numbers without multiplication and division": "https://leetcode.com/problems/divide-two-integers/",
    "Power Set Bit Manipulation": "https://www.geeksforgeeks.org/power-set/",
    "XOR of numbers in a given range": "https://www.geeksforgeeks.org/xor-of-all-subarray-xors/",
    "Assign Cookies": "https://leetcode.com/problems/assign-cookies/",
    "Lemonade Change": "https://leetcode.com/problems/lemonade-change/",
    "Jump Game - I": "https://leetcode.com/problems/jump-game/",
    "Shortest Job First": "https://www.geeksforgeeks.org/program-for-shortest-job-first-sjf-scheduling-set-1/",
    "Job sequencing Problem": "https://www.geeksforgeeks.org/job-sequencing-problem/",
    "N meetings in one room": "https://practice.geeksforgeeks.org/problems/n-meetings-in-one-room-1587115620/1",
    "Non-overlapping Intervals": "https://leetcode.com/problems/non-overlapping-intervals/",
    "Insert Interval": "https://leetcode.com/problems/insert-interval/",
    "Minimum number of platforms required for a railway": "https://www.geeksforgeeks.org/minimum-number-platforms-required-railwaybus-station/",
    "Valid Paranthesis Checker": "https://leetcode.com/problems/valid-parentheses/",
    "Candy": "https://leetcode.com/problems/candy/",
    "Theory": "https://www.geeksforgeeks.org/theory-of-computation/",
    "Maximum Points You Can Obtain from Cards": "https://leetcode.com/problems/maximum-points-you-can-obtain-from-cards/",
    "Longest Substring Without Repeating Characters": "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
    "Max Consecutive Ones III": "https://leetcode.com/problems/max-consecutive-ones-iii/",
    "Fruit Into Baskets": "https://leetcode.com/problems/fruit-into-baskets/",
    "Longest Substring With At Most K Distinct Characters": "https://leetcode.com/problems/longest-substring-with-at-most-k-distinct-characters/",
    "Longest Repeating Character Replacement": "https://leetcode.com/problems/longest-repeating-character-replacement/",
    "Minimum Window Substring": "https://leetcode.com/problems/minimum-window-substring/",
    "Number of Substrings Containing All Three Characters": "https://leetcode.com/problems/number-of-substrings-containing-all-three-characters/",
    "Binary Subarrays With Sum": "https://leetcode.com/problems/binary-subarrays-with-sum/",
    "Count number of Nice subarrays": "https://leetcode.com/problems/count-number-of-nice-subarrays/",
    "Implementation using different DS": "https://www.geeksforgeeks.org/data-structures/",
    "Implement Stack using Arrays": "https://www.geeksforgeeks.org/stack-data-structure-introduction-program/",
    "Implement Queue using Arrays": "https://www.geeksforgeeks.org/queue-set-1introduction-and-array-implementation/",
    "Implement Stack using Queue": "https://leetcode.com/problems/implement-stack-using-queues/",
    "Implement Queue using Stack": "https://leetcode.com/problems/implement-queue-using-stacks/",
    "Implement stack using Linkedlist": "https://www.geeksforgeeks.org/implement-a-stack-using-singly-linked-list/",
    "Implement queue using Linkedlist": "https://www.geeksforgeeks.org/queue-linked-list-implementation/",
    "Balanced Paranthesis": "https://leetcode.com/problems/valid-parentheses/",
    "Next Greater Element": "https://leetcode.com/problems/next-greater-element-i/",
    "Next Greater Element - 2": "https://leetcode.com/problems/next-greater-element-ii/",
    "Asteroid Collision": "https://leetcode.com/problems/asteroid-collision/",
    "Sum of Subarray Minimums": "https://leetcode.com/problems/sum-of-subarray-minimums/",
    "Sum of Subarray Ranges": "https://leetcode.com/problems/sum-of-subarray-ranges/",
    "Remove K Digits": "https://leetcode.com/problems/remove-k-digits/",
    "Implement Min Stack": "https://leetcode.com/problems/min-stack/",
    "Sliding Window Maximum": "https://leetcode.com/problems/sliding-window-maximum/",
    "Trapping Rainwater": "https://leetcode.com/problems/trapping-rain-water/",
    "Largest rectangle in a histogram": "https://leetcode.com/problems/largest-rectangle-in-histogram/",
    "Maximum Rectangles": "https://leetcode.com/problems/maximal-rectangle/",
    "Stock span problem": "https://www.geeksforgeeks.org/the-stock-span-problem/",
    "Celebrity Problem": "https://www.geeksforgeeks.org/the-celebrity-problem/",
    "LRU Cache": "https://leetcode.com/problems/lru-cache/",
    "LFU Cache": "https://leetcode.com/problems/lfu-cache/",
    "Introduction": "https://www.geeksforgeeks.org/introduction-to-tree-data-structure/",
    "Preorder Traversal": "https://leetcode.com/problems/binary-tree-preorder-traversal/",
    "Inorder Traversal": "https://leetcode.com/problems/binary-tree-inorder-traversal/",
    "Postorder Traversal": "https://leetcode.com/problems/binary-tree-postorder-traversal/",
    "Level Order Traversal": "https://leetcode.com/problems/binary-tree-level-order-traversal/",
    "Pre, Post, Inorder in one traversal": "https://www.geeksforgeeks.org/iterative-preorder-inorder-and-postorder-traversal-of-a-binary-tree/",
    "Maximum Depth in BT": "https://leetcode.com/problems/maximum-depth-of-binary-tree/",
    "Check if two trees are identical or not": "https://leetcode.com/problems/same-tree/",
    "Check for balanced binary tree": "https://leetcode.com/problems/balanced-binary-tree/",
    "Diameter of Binary Tree": "https://leetcode.com/problems/diameter-of-binary-tree/",
    "Maximum path sum": "https://leetcode.com/problems/binary-tree-maximum-path-sum/",
    "Check for symmetrical BTs": "https://leetcode.com/problems/symmetric-tree/",
    "Zig Zag or Spiral Traversal": "https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/",
    "Boundary Traversal": "https://www.geeksforgeeks.org/boundary-traversal-of-binary-tree/",
    "Vertical Order Traversal": "https://leetcode.com/problems/vertical-order-traversal-of-a-binary-tree/",
    "Top View of BT": "https://www.geeksforgeeks.org/print-nodes-top-view-binary-tree/",
    "Bottom view of BT": "https://www.geeksforgeeks.org/bottom-view-binary-tree/",
    "Right/Left View of BT": "https://leetcode.com/problems/binary-tree-right-side-view/",
    "Print root to node path in BT": "https://www.geeksforgeeks.org/print-path-root-given-node-binary-tree/",
    "LCA in BT": "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/",
    "Maximum Width of BT": "https://leetcode.com/problems/maximum-width-of-binary-tree/",
    "Print all nodes at a distance of K in BT": "https://leetcode.com/problems/all-nodes-distance-k-in-binary-tree/",
    "Minimum time taken to burn the BT from a given Node": "https://www.geeksforgeeks.org/burn-the-binary-tree-starting-from-the-target-node/",
    "Count total nodes in a complete BT": "https://leetcode.com/problems/count-complete-tree-nodes/",
    "Requirements needed to construct a unique BT": "https://www.geeksforgeeks.org/if-you-are-given-two-traversal-sequences-can-you-construct-the-binary-tree/",
    "Construct a BT from Preorder and Inorder": "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/",
    "Construct a BT from Postorder and Inorder": "https://leetcode.com/problems/construct-binary-tree-from-inorder-and-postorder-traversal/",
    "Serialize and De-serialize BT": "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/",
    "Morris Inorder Traversal": "https://www.geeksforgeeks.org/inorder-tree-traversal-without-recursion-and-without-stack/",
    "Morris Preorder Traversal": "https://www.geeksforgeeks.org/morris-traversal-for-preorder/",
    "Introduction to BST": "https://www.geeksforgeeks.org/introduction-to-binary-search-tree-data-structure/",
    "Search in BST": "https://leetcode.com/problems/search-in-a-binary-search-tree/",
    "Floor and Ceil in a BST": "https://www.geeksforgeeks.org/floor-and-ceil-from-a-bst/",
    "Insert a given node in BST": "https://leetcode.com/problems/insert-into-a-binary-search-tree/",
    "Delete a node in BST": "https://leetcode.com/problems/delete-node-in-a-bst/",
    "Kth Smallest and Largest element in BST": "https://leetcode.com/problems/kth-smallest-element-in-a-bst/",
    "Check if a tree is a BST or not": "https://www.geeksforgeeks.org/a-program-to-check-if-a-binary-tree-is-bst-or-not/",
    "LCA in BST": "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/",
    "Construct a BST from a preorder traversal": "https://leetcode.com/problems/construct-binary-search-tree-from-preorder-traversal/",
    "Inorder successor and predecessor in BST": "https://www.geeksforgeeks.org/inorder-successor-predecessor-given-key-bst/",
    "BST iterator": "https://leetcode.com/problems/binary-search-tree-iterator/",
    "Two sum in BST": "https://leetcode.com/problems/two-sum-iv-input-is-a-bst/",
    "Correct BST with two nodes swapped": "https://leetcode.com/problems/recover-binary-search-tree/",
    "Largest BST in Binary Tree": "https://www.geeksforgeeks.org/largest-bst-binary-tree-set-2/",
    "Heaps (Theory Video)": "https://www.geeksforgeeks.org/heap-data-structure/",
    "Heapify Algorithm": "https://www.geeksforgeeks.org/heap-sort/",
    "Build heap from a given Array": "https://www.geeksforgeeks.org/building-heap-from-array/",
    "Implement Min Heap": "https://www.geeksforgeeks.org/min-heap-in-java/",
    "Implement Max Heap": "https://www.geeksforgeeks.org/max-heap-in-java/",
    "Check if an array represents a min heap": "https://www.geeksforgeeks.org/how-to-check-if-a-given-array-represents-a-binary-heap/",
    "Convert Min Heap to Max Heap": "https://www.geeksforgeeks.org/convert-min-heap-to-max-heap/",
    "Heap Sort": "https://www.geeksforgeeks.org/heap-sort/",
    "K-th Largest element in an array": "https://leetcode.com/problems/kth-largest-element-in-an-array/",
    "Kth largest element in a stream of running integers": "https://leetcode.com/problems/kth-largest-element-in-a-stream/",
    "Introduction to Graph": "https://www.geeksforgeeks.org/graph-data-structure-and-algorithms/",
    "Connected Components": "https://www.geeksforgeeks.org/connected-components-in-an-undirected-graph/",
    "Traversal Techniques": "https://www.geeksforgeeks.org/graph-traversals/",
    "Number of provinces": "https://leetcode.com/problems/number-of-provinces/",
    "Number of islands": "https://leetcode.com/problems/number-of-islands/",
    "Flood fill algorithm": "https://leetcode.com/problems/flood-fill/",
    "Number of enclaves": "https://leetcode.com/problems/number-of-enclaves/",
    "Rotten Oranges": "https://leetcode.com/problems/rotting-oranges/",
    "Distance of nearest cell having one": "https://www.geeksforgeeks.org/distance-nearest-cell-1-binary-matrix/",
    "Surrounded Regions": "https://leetcode.com/problems/surrounded-regions/",
    "Number of distinct islands": "https://leetcode.com/problems/number-of-distinct-islands/",
    "Detect a cycle in an undirected graph": "https://www.geeksforgeeks.org/detect-cycle-undirected-graph/",
    "Bipartite graph": "https://www.geeksforgeeks.org/bipartite-graph/",
    "Topological sort or Kahn's algorithm": "https://www.geeksforgeeks.org/topological-sorting-indegree-based-solution/",
    "Detect a cycle in a directed graph": "https://www.geeksforgeeks.org/detect-cycle-in-a-graph/",
    "Find eventual safe states": "https://leetcode.com/problems/find-eventual-safe-states/",
    "Course Schedule I": "https://leetcode.com/problems/course-schedule/",
    "Course Schedule II": "https://leetcode.com/problems/course-schedule-ii/",
    "Alien Dictionary": "https://leetcode.com/problems/alien-dictionary/",
    "Shortest path in DAG": "https://www.geeksforgeeks.org/shortest-path-for-directed-acyclic-graphs/",
    "Shortest path in undirected graph with unit weights": "https://www.geeksforgeeks.org/shortest-path-unweighted-graph/",
    "Word ladder I": "https://leetcode.com/problems/word-ladder/",
    "Word ladder II": "https://leetcode.com/problems/word-ladder-ii/",
    "Dijkstra's algorithm": "https://www.geeksforgeeks.org/dijkstras-shortest-path-algorithm-greedy-algo-7/",
    "Print Shortest Path": "https://www.geeksforgeeks.org/printing-paths-dijkstras-shortest-path-algorithm/",
    "Shortest Distance in a Binary Maze": "https://www.geeksforgeeks.org/shortest-path-in-a-binary-maze/",
    "Path with minimum effort": "https://leetcode.com/problems/path-with-minimum-effort/",
    "Cheapest flight within K stops": "https://leetcode.com/problems/cheapest-flights-within-k-stops/",
    "Minimum multiplications to reach end": "https://www.geeksforgeeks.org/minimum-multiplications-to-reach-end/",
    "Number of ways to arrive at destination": "https://leetcode.com/problems/number-of-ways-to-arrive-at-destination/",
    "Bellman ford algorithm": "https://www.geeksforgeeks.org/bellman-ford-algorithm-dp-23/",
    "Floyd warshall algorithm": "https://www.geeksforgeeks.org/floyd-warshall-algorithm-dp-16/",
    "Find the city with the smallest number of neighbors": "https://leetcode.com/problems/find-the-city-with-the-smallest-number-of-neighbors-at-a-threshold-distance/",
    "MST theory": "https://www.geeksforgeeks.org/kruskals-minimum-spanning-tree-algorithm-greedy-algo-2/",
    "Disjoint Set": "https://www.geeksforgeeks.org/disjoint-set-union-find/",
    "Find the MST weight": "https://www.geeksforgeeks.org/kruskals-minimum-spanning-tree-algorithm-greedy-algo-2/",
    "Number of operations to make network connected": "https://leetcode.com/problems/number-of-operations-to-make-network-connected/",
    "Accounts merge": "https://leetcode.com/problems/accounts-merge/",
    "Number of islands II": "https://leetcode.com/problems/number-of-islands-ii/",
    "Making a large island": "https://leetcode.com/problems/making-a-large-island/",
    "Most stones removed with same row or column": "https://leetcode.com/problems/most-stones-removed-with-same-row-or-column/",
    "Kosaraju's algorithm": "https://www.geeksforgeeks.org/strongly-connected-components/",
    "Bridges in graph": "https://www.geeksforgeeks.org/bridge-in-a-graph/",
    "Articulation point in graph": "https://www.geeksforgeeks.org/articulation-points-or-cut-vertices-in-a-graph/",
    "Introduction to DP": "https://www.geeksforgeeks.org/dynamic-programming/",
    "Climbing stairs": "https://leetcode.com/problems/climbing-stairs/",
    "Frog Jump": "https://leetcode.com/problems/frog-jump/",
    "Frog jump with K distances": "https://www.geeksforgeeks.org/minimum-jumps-to-reach-end-of-array/",
    "Maximum sum of non adjacent elements": "https://www.geeksforgeeks.org/find-maximum-possible-stolen-value-houses/",
    "House robber": "https://leetcode.com/problems/house-robber/",
    "Ninja's training": "https://www.codingninjas.com/codestudio/problems/ninja-s-training_3621003",
    "Grid unique paths": "https://leetcode.com/problems/unique-paths/",
    "Unique paths II": "https://leetcode.com/problems/unique-paths-ii/",
    "Minimum path sum in grid": "https://leetcode.com/problems/minimum-path-sum/",
    "Triangle": "https://leetcode.com/problems/triangle/",
    "Cherry pickup II": "https://leetcode.com/problems/cherry-pickup-ii/",
    "Best time to buy and sell stock": "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
    "Best time to buy and sell stock II": "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii/",
    "Best time to buy and sell stock III": "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iii/",
    "Best time to buy and sell stock IV": "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iv/",
    "Best time to buy and sell stock with transaction fees": "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-transaction-fee/",
    "Subset sum equals to target": "https://www.geeksforgeeks.org/subset-sum-problem-dp-25/",
    "Partition equal subset sum": "https://leetcode.com/problems/partition-equal-subset-sum/",
    "Partition a set into two subsets with minimum absolute sum difference": "https://www.geeksforgeeks.org/partition-a-set-into-two-subsets-such-that-the-difference-of-subset-sums-is-minimum/",
    "Count subsets with sum K": "https://www.geeksforgeeks.org/count-of-subsets-with-sum-equal-to-x/",
    "Count partitions with given difference": "https://www.geeksforgeeks.org/count-subsets-difference-given-value/",
    "0 and 1 Knapsack": "https://www.geeksforgeeks.org/0-1-knapsack-problem-dp-10/",
    "Minimum coins": "https://www.geeksforgeeks.org/find-minimum-number-of-coins-that-make-a-change/",
    "Target sum": "https://leetcode.com/problems/target-sum/",
    "Coin change II": "https://leetcode.com/problems/coin-change-2/",
    "Unbounded knapsack": "https://www.geeksforgeeks.org/unbounded-knapsack-repetition-items-allowed/",
    "Rod cutting problem": "https://www.geeksforgeeks.org/cutting-a-rod-dp-13/",
    "Longest Increasing Subsequence": "https://leetcode.com/problems/longest-increasing-subsequence/",
    "Print Longest Increasing Subsequence": "https://www.geeksforgeeks.org/printing-longest-increasing-subsequence/",
    "Largest Divisible Subset": "https://leetcode.com/problems/largest-divisible-subset/",
    "Longest String Chain": "https://leetcode.com/problems/longest-string-chain/",
    "Longest Bitonic Subsequence": "https://www.geeksforgeeks.org/longest-bitonic-subsequence-dp-15/",
    "Number of Longest Increasing Subsequences": "https://leetcode.com/problems/number-of-longest-increasing-subsequence/",
    "Longest common subsequence": "https://leetcode.com/problems/longest-common-subsequence/",
    "Longest common substring": "https://www.geeksforgeeks.org/longest-common-substring-dp-29/",
    "Longest palindromic subsequence": "https://leetcode.com/problems/longest-palindromic-subsequence/",
    "Minimum insertions to make string palindrome": "https://leetcode.com/problems/minimum-insertion-steps-to-make-a-string-palindrome/",
    "Minimum insertions or deletions to convert string A to B": "https://www.geeksforgeeks.org/minimum-number-deletions-insertions-transform-one-string-another/",
    "Shortest common supersequence": "https://leetcode.com/problems/shortest-common-supersequence/",
    "Distinct subsequences": "https://leetcode.com/problems/distinct-subsequences/",
    "Edit distance": "https://leetcode.com/problems/edit-distance/",
    "Wildcard matching": "https://leetcode.com/problems/wildcard-matching/",
    "Matrix chain multiplication": "https://www.geeksforgeeks.org/matrix-chain-multiplication-dp-8/",
    "Minimum cost to cut the stick": "https://leetcode.com/problems/minimum-cost-to-cut-a-stick/",
    "Burst balloons": "https://leetcode.com/problems/burst-balloons/",
    "Palindrome partitioning II": "https://leetcode.com/problems/palindrome-partitioning-ii/",
    "Trie Implementation and Operations": "https://www.geeksforgeeks.org/trie-insert-and-search/",
    "Trie Implementation and Advanced Operations": "https://www.geeksforgeeks.org/trie-insert-and-search/",
    "Longest word with all prefixes": "https://leetcode.com/problems/longest-word-in-dictionary/",
    "Number of distinct substrings in a string": "https://www.geeksforgeeks.org/count-distinct-substrings-string-using-suffix-trie/",
    "Maximum XOR of two numbers in an array": "https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/",
    "Maximum Xor with an element from an array": "https://leetcode.com/problems/maximum-xor-with-an-element-from-array/",
    "Reverse every word in a string": "https://www.geeksforgeeks.org/reverse-words-given-string-java/",
    "Minimum number of bracket reversals to make an expression balanced": "https://www.geeksforgeeks.org/minimum-number-of-bracket-reversals-needed-to-make-an-expression-balanced/",
    "Count and say": "https://leetcode.com/problems/count-and-say/",
    "Rabin Karp Algorithm": "https://www.geeksforgeeks.org/rabin-karp-algorithm-for-pattern-searching/",
    "Z function": "https://www.geeksforgeeks.org/z-algorithm-linear-time-pattern-searching-algorithm/",
    "KMP Algorithm or LPS array": "https://www.geeksforgeeks.org/kmp-algorithm-for-pattern-searching/",
    "Shortest Palindrome": "https://leetcode.com/problems/shortest-palindrome/",
    "Longest happy prefix": "https://leetcode.com/problems/longest-happy-prefix/",
    "Print all primes till N": "https://www.geeksforgeeks.org/sieve-of-eratosthenes/",
    "Prime factorisation of a Number": "https://www.geeksforgeeks.org/prime-factorization-using-sieve-olog-n-multiple-queries/",
    "Count primes in range L to R": "https://www.geeksforgeeks.org/segmented-sieve/"
}
